Overhaul Travis & Codecov setup
gap-packages/FactInt pull request #5
Opened 2017-12-13 09:19 UTC by fingolfin

For Codecov, actually enable status messages in pull requests (so far,
all were turned off, but for some reason codecov ignores this; still,
better to specify actual intent in the file).

For Travis, adapt scripts/build_pkg.sh to work with packages not using
autoconf, so that we can use the same script across many packages. Also
don't copy the tested package into GAP's pkg dir; instead, put it into
its own GAP root which we tell GAP to look at before its usual GAP root.

Modify scripts/gather-coverage.sh and scripts/run_tests.sh to use this
modified list of GAP root dirs

Simplify scripts/build_gap.sh significantly by using BuildPackages.sh.

2017-12-13 09:28 UTC, fingolfin commented
Please do not merge this just yet: the profiling compilation failed (due to `clang++` issue), which is a problem in itself, but also the fact that this did not cause the build to be marked as failed.

Of course it's a questionable why this package is tested with clang in the first place, as it contains no compiled code?

2017-12-13 10:25 UTC, fingolfin commented
This is now waiting on https://github.com/gap-system/gap/pull/2022

2017-12-13 15:34 UTC, alex-konovalov commented
> Of course it's a questionable why this package is tested with clang in the first place, as it contains no compiled code?

Setup was inherited from some other package, which used compiled code. It makes no harm to test a package without compiled code on different setting as well, isn't it? For example, FactInt, I assume, may exercise GMP heavily.

2017-12-14 14:59 UTC, fingolfin commented
I don't think it exercises GMP more heavily than the GAP test suite. It mostly performs elementary operations only.

Anyway, this PR is now IMHO ready for merge.

2017-12-14 23:35 UTC, alex-konovalov commented
OK - I want to edit the history a bit, should that be done now, or after?

2017-12-15 09:30 UTC, fingolfin commented
Which history? That of the master branch of this package? Or of this PR? I am fine either way, just if you do it before merging the PR, let me know, because I'll have to rebase it.

That said, actually I'd like to edit this PR *some more* to make it trivial to add tests against the stable branch and/or HPC-GAP in the future (if desired). So, just go ahead with editing the `master` history :-)

2017-12-15 15:43 UTC, alex-konovalov commented
@fingolfin I want to edit master history to make changes within last two weeks atomic. I will ask you and @Stefan-Kohl to reset your repositories then.

2018-01-07 20:08 UTC, Stefan-Kohl commented
Should I merge this?

2018-01-08 23:54 UTC, alex-konovalov commented
@fingolfin not yet, please- I want first to understand why Example package fails, with the same setup.

2018-01-16 23:37 UTC, olexandr-konovalov requested changes
Please rebase after resetting the master branch of your clone/fork.

2018-01-17 15:14 UTC, fingolfin commented
Rebased

2018-01-17 15:46 UTC, olexandr-konovalov approved these changes

2018-01-17 15:48 UTC, merged